name: Generate sitemap.xml

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "30 3 * * 1"  # måndag 03:30 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Generate sitemap
        env:
          BASE_URL: ${{ vars.PAGES_BASE_URL }}
        run: |
          node --version
          node scripts/generate-sitemap.js
      - name: Commit sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update sitemap.xml"
          file_pattern: sitemap.xml
